### PR TITLE
Add food-produced bar chart

### PR DESCRIPTION
**Pull request by oliverroick**
Adds the food-produced bar chart to the area page

Screenshot 2024-10-21 at 18 15 02

- Removed the total-flow aggregate query, we're calculating the number now based on the individual food-group numbers
- Add query to get food-group production value
- Add query to get food groups, needed to calculate the aggregate
- Add functionality to calculate food-group aggregate
  - `findParent` find the top-most ancestor for a given food group
  - We're then aggregating the numbers according to the parent IDs
- Add number formatting to `ListBars`, using `formatKeyIndicator`

### CODE REVIEW

**Comment by vgeorge** [comment]
@oliverroick I did a quick function review and wasn't able to see more then one food group listed for areas that should have them. I tried [Québec](localhost:3000/area/CAN.11_1) but it doesn't show any bars:

Screenshot 2024-10-22 at 13 26 28

Do you know of any other areas that have more than one food group and are working as intented?

**Comment by vgeorge** [comment]
@oliverroick I looked into the area you referred to and it displayed the data correctly; this looks good. We might need an empty state for when there is no flow data available, for which I ticketed in separate in https://github.com/earth-genome/foodtwin-global-app/issues/85.  

With the merge to #78 there are conflicting changes with this. I tried to solve it, but it seemed that I was introducing regressions in your work. Would you be able to merge develop into this?

**Comment by oliverroick** [comment]
@vgeorge I've sorted out the merge conflict here.

**Review by vgeorge — APPROVED** [review]
@oliverroick thanks! I confirm I can see the two bars when visiting the link you provided.

**Pull request merged**
