### PR TITLE
feat: Include sidebar width in fit-bounds padding

### LINKED ISSUE #69: Bug: Zooming to production areas clips the production area
When users click on a producing area, the map is zoomed to that area (added in https://github.com/earth-genome/foodtwin-global-app/pull/52).

Currently, the amount of zooming and centering doesn't seem to account for the right-hand side panel.

Screen Recording 2024-10-01 at 09 20 14

### PR DESCRIPTION
**Pull request by oliverroick**
Fixes #69 

- Adds `SIDEBAR_WIDTH` setting to configure the width of the sidebar
- Include the width in the fit-bounds padding

### CODE REVIEW

**Review by vgeorge — CHANGES_REQUESTED** [review]
@oliverroick while I see that the map fits the area correctly with padding, I noticed it doesn't stretch correctly when closing it:

fit-bounds

**Comment by oliverroick** [comment]
@vgeorge I've added a change to fix this. The container size wasn't updated when the area sidebar is closed, which I think is because the component is rendered on server-side. I changed this now to absolute positioning of the map and the sidebar, and adapt the legend positioning dynamically.

**Comment by vgeorge** [comment]
@oliverroick there was an issue with the legend position with offset approach, it was being displayed aligned to the left border:

Screenshot 2024-10-16 at 16 33 54

I added two changes to try fixing the issue I reported and the legend alignment:

- Blank side panel area: you were correct that the width of the side panel were not being considered by the map component. After I added `mapRef.resize()` on world and area page load, the map is rendered correctly
- Legend alignment: I replaced the offset approach with using flex layout to align the legend and the sidebar, avoiding passing the sidebar constant to different components

Please let me know if you find any issues. This looks good to merge otherwise.

**Comment by oliverroick** [comment]
@vgeorge Thanks for the fix, this is working well for me.

**Pull request merged**
