### PR TITLE
chore: Add color config for nutrition and food groups

### PR DESCRIPTION
**Pull request by oliverroick**
Implements [#34](https://github.com/earth-genome/foodtwin-global-app/issues/34)

Adds colour config for food groups and nutrition to the tailwind config.

### CODE REVIEW

**Review by vgeorge — CHANGES_REQUESTED** [review]
@oliverroick I added the food groups to the database schema in #39. Here is a table dump: [FoodGroup.csv](https://github.com/user-attachments/files/16931994/FoodGroup.csv).

I believe it's fine to hardcode the colors in the theme file, but we need to use the food group names from the table to match the colors consistently.

**Comment by oliverroick** [comment]
I used the food groups that were specified in the designs. We can and should use food groups that are specified in the data, but in order to do so, we need to:

1. Provide the food-group names in a way that is compatible with CSS class-name conventions, ie. without white spaces or commas, I suggest we add `key` field or so that provides this key.
2. @faustoperez needs to provide the colours for all of these groups.

**Comment by faustoperez** [comment]
> @faustoperez needs to provide the colours for all of these groups.

These are the colours for the 10 main categories. Note that @cameronkruse suggested that "Sugars and sweeteners" was moved to "Others" and move "Grains" to its own category

Particles

Link to Figma file 👉 https://www.figma.com/design/zz7755JriAt4vKJsdV3Dcr/Global-Food-Twin?node-id=978-1093&t=YNlZVM29GFwEfA4A-1

**Comment by vgeorge** [comment]
@oliverroick I added a `slug` property to the food group with a web-friendly string in #44.

**Comment by oliverroick** [comment]
@vgeorge I've updated the config based on the [discussion here](https://developmentseed.slack.com/archives/C050GPQJGS2/p1727332008566389). These new groups still need to be imported in the database.

**Review by vgeorge — APPROVED** [review]

**Pull request merged**
