### PR TITLE
Move globe view to the home page

### PR DESCRIPTION
**Pull request by vgeorge**
Contributes to:

- #5 
- #9

Changes:
- Promote globe view from the sandbox to the home page
- Add rewrite rule `/area/:areaId -> /` to avoid rerendering the globe view when the route changes
- Added custom environment variable to enable Stately Inspector
- Moved sandbox index to `/sandbox` route

How to test:
- Visit the home page, click on any country, the browser URL should change without reloading the page
- Visit http://localhost:3000/sandbox, it should display the index of exercise pages
- Set `NEXT_PUBLIC_USE_STATELY_INSPECTOR=true` in `.env`, the Stately Inspector should open in a separate tab

Known issues:
- The home page doesn't use MVT layers, we can add them after we decide which library works best
- If you visit a route like `/area/CA` directly, the country won't appear selected in the map, but it should be straightforward to implement later

@oliverroick this is ready for review. The [rewrite rules](https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites) approach seems the cleanest to make the app work like a SPA, but I'm happy to discuss alternatives.

### CODE REVIEW

**Review by oliverroick — COMMENTED** [review]
This looks ok, but I have some concerns about the rewrite approach.

It looks like currently, when selecting a country, we're updating the state and we're updating the browser history in the globe page. Does do mean we have to follow the same approach when we're showing shipping routes, production areas, nodes etc?

It's seems like:

a. we're implementing our own router  
b. the globe component will deal with all of the routing

React-router seems like the better choice for the behaviour we want here, and there are [examples for that](https://dev.to/toomuchdesign/next-js-react-router-2kl8), but it seems to defeat the purpose of NextJS to some extent.

**Comment by vgeorge** [comment]
@oliverroick  thanks for the review. I agree that the rewrite approach doesn't look right and that trying to build the app as an SPA defeats the purpose of Next.js. Looking at the framework documentation, I believe we should try moving towards a mix of client and server components. The (globe) map component could be a client component added to layout.tsx, which should make it reusable in different routes and avoid re-rendering. The side panel could work with server components and small client components where interaction is needed.

**Comment by oliverroick** [comment]
@vgeorge Would it be worth preparing an example for the client/server component approach?

**Comment by vgeorge** [comment]
@oliverroick I added changes to implement the server component approach. Now the only client part should be the globe. I also reorganized the layout files so the globe is part of the home and area page, but is not from the about page. This will allow us to control better which routes use the globe or not. I also started connecting the side panel to the database, it should load the area name from the route accessed. Please let me know your thoughts.

**Review by oliverroick — COMMENTED** [review]
I think this is the better approach. I found some small issues:

- When I select an area, the stays in position and is partly overlapped by the right-hand panel. (This doesn’t happen when I enter an area page directly, ie. without clicking on the globe). Likewise when I close the panel, globe should be in the centre of the page. 
- The globe should be centred around the selected area, so when I select a country the map view should transition to the area. Is it worth adding this here or in a new PR?

**Comment by vgeorge** [comment]
@oliverroick I created #24 to handle map bounds on area click and the displacement you noticed. Since this requires a new API route, I suggest we work on it separately. In my last commits, I replaced Mapbox GL with MapLibre and changed it to a flat view. This decision is documented at https://github.com/earth-genome/foodtwin-global-app/issues/5#issuecomment-2284731643. Please let me know if you think we need additional changes here.

**Comment by oliverroick** [comment]
Thanks Vitor, working on the bounds problem separately sounds good.

**Review by oliverroick — APPROVED** [review]

**Pull request merged**
